### ISSUE TITLE
landsat --update-metadata is not a valid command

### ISSUE THREAD

**Issue by oeon** [developmentseed/landsat-api#1]
https://github.com/developmentseed/landsat-api#updating-the-metadata documents the command: `landsat --update-metadata` but `landsat -h` does not mention this command and returns:

```
usage: landsat [-h] {search,download,process} ...
landsat: error: too few arguments
```

**Comment by scisco** [comment]
@oeon You are right. We did not include the feature on the latest version of landsat-util. I will add it in the next release. In the meantime, the library for updating the metadata is present landsat-util. 

You can clone the landsat-util repo and run use this code in python file:

``` python
from landsat.metadata_helper import Metadata

m = Metadata()
m.populate()
```
