### ISSUE TITLE
landsat-api cron job for updating the meta data is failing

### ISSUE THREAD

**Issue by scisco** [developmentseed/landsat-api#2]
The public version of the api has not been updated for sometime because the cron job is failing on our server. Has to be fixed

**Comment by kamicut** [comment]
@scisco were you able to fix the cron job?

**Comment by scisco** [comment]
yes! 130K new records were added  :)

**Comment by kamicut** [comment]
Great, I think we can close https://github.com/developmentseed/landsat-util/issues/24
