### ISSUE TITLE
On new version of landsat-api, it seems as though some scenes are not getting added

### ISSUE THREAD

**Issue by jflasher** [developmentseed/landsat-api#22]
For example, this works /landsat?scene_id=LC80120432015128LGN00

but the following valid Landsat scenes are all return `No Match Found`

LC81380202013173LGN00
LC81670132015158LGN00
LC80290332015119LGN00
LC81630202015002LGN00
LC81380202013173LGN00
LC80170302015211LGN00
LC81730192014197LGN00
LC80250302015139LGN00
LC81660182014340LGN00
LC81660182015039LGN00
LC81130302014209LGN00
LC81260592015047LGN00
LC81260562015223LGN00

**Comment by scisco** [comment]
It must have been an indexing issue. Searched for the scenes on a fully indexed instance and was able to find them.
