### ISSUE TITLE
 "SERVER_ERROR": "Check your request and try again"

### ISSUE THREAD

**Issue by akudrya** [developmentseed/landsat-api#4]
Hi, guys! This is Alex from Dauria project. I'm trying to launch landsat-api.
1. I faced with one elastic search error (problems with connectivity) and changed "keep alive" to false and   your api.js stated launching.
2. My elasticsearch service is working: for localhost:9200 I receive
{
  "status" : 200,
  "name" : "Acrobat",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.4",
    "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
    "build_timestamp" : "2015-02-19T13:05:36Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.3"
  },
  "tagline" : "You Know, for Search"
}
3. Then I start api.js, make a test request and receive
{
  "error": {
    "code": "SERVER_ERROR",
    "message": "Check your request and try again"
  }
}
In the console: 
{"name":"openfda-api-logger","hostname":"akudrya-2.local","pid":49234,"level":30,"user-agent":"curl/7.39.0","host":"localhost:8000","accept":"_/_","msg":"Request Headers","time":"2015-03-12T17:54:00.650Z","v":0}
{"name":"openfda-api-logger","hostname":"akudrya-2.local","pid":49234,"level":30,"search":"LC81660362014196LGN00","msg":"Request Query","time":"2015-03-12T17:54:00.651Z","v":0}
{"name":"openfda-api-logger","hostname":"akudrya-2.local","pid":49234,"level":30,"msg":"{\"query\":{\"query_string\":{\"query\":\"LC81660362014196LGN00\"}}} Elasticsearch Query","time":"2015-03-12T17:54:00.656Z","v":0}
{"name":"openfda-api-logger","hostname":"akudrya-2.local","pid":49234,"level":30,"msg":"Request complete","time":"2015-03-12T17:54:00.684Z","v":0}
{"name":"openfda-api-logger","hostname":"akudrya-2.local","pid":49234,"level":50,"err":{"message":"IndexMissingException[[landsat] missing]","name":"Error","stack":"Error: IndexMissingException[[landsat] missing]\n    at respond (/Users/akudrya/GitHub/landsat-api/node_modules/elasticsearch/src/lib/transport.js:233:15)\n    at checkRespForFailure (/Users/akudrya/GitHub/landsat-api/node_modules/elasticsearch/src/lib/transport.js:201:7)\n    at HttpConnector.<anonymous> (/Users/akudrya/GitHub/landsat-api/node_modules/elasticsearch/src/lib/connectors/http.js:147:7)\n    at IncomingMessage.bound (/Users/akudrya/GitHub/landsat-api/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickCallback (node.js:355:11)"},"msg":"IndexMissingException[[landsat] missing]","time":"2015-03-12T17:54:00.688Z","v":0}

I've installed all the dependencies. The only possible problem is that I have node.js 0.12.0 instead of 0.8.0

Could you help me please?

**Comment by scisco** [comment]
@akudrya 
Did you run the update to add metadata first?

**Comment by scisco** [comment]
@akudrya 

To give you more context, please follow the steps here: https://github.com/developmentseed/landsat-api/tree/master/updater

**Comment by akudrya** [comment]
Thanks!
Now I have this problem 
akudrya-2:landsat-api akudrya$ sudo python updater/update.py
downloading http://landsat.usgs.gov/metadata_service/bulk_metadata_files/LANDSAT_8.csv
Traceback (most recent call last):
  File "updater/update.py", line 20, in <module>
    main()
  File "updater/update.py", line 17, in main
    meta.populate()
  File "/Users/akudrya/GitHub/landsat-api/updater/metadata_helper.py", line 36, in populate
    if self.download():
  File "/Users/akudrya/GitHub/landsat-api/updater/metadata_helper.py", line 110, in download
    total_size = self.get_url_file_size(f)
  File "/Users/akudrya/GitHub/landsat-api/updater/metadata_helper.py", line 147, in get_url_file_size
    return float(size)
TypeError: float() argument must be a string or a number

It returns size=None

**Comment by akudrya** [comment]
It appears that metadata_helper.py requires a known value for remote_file.headers.get('content-length') before it started downloading. 
There's something wrong with http://landsat.usgs.gov/metadata_service/bulk_metadata_files/LANDSAT_8.csv - it doesn't show the file size in advance.

**Comment by scisco** [comment]
@akudrya Thanks for catching the error. It should be resolved now.
