### ISSUE TITLE
Live API: no data available for Jun 2018

### ISSUE THREAD

**Issue by lucasvr** [developmentseed/landsat-api#44]
I have been looking into using the Live API services to get recent scenes from Landsat-8 but it looks like there is no data available for the month of June. May works just fine:

https://sat-api.developmentseed.org/search/stac?datetime=2018-05&collection=landsat-8&eo:cloud_cover=0&limit=2
https://sat-api.developmentseed.org/search/stac?datetime=2018-06&collection=landsat-8&eo:cloud_cover=0&limit=2

Is this expected? How often do you guys update the indexes used by the Live API? Thanks!

**Comment by matthewhanson** [comment]
Hi @lucasvr , it does seem that there's an issue with ingesting Landsat data from June. I have a fix and will be deploying a new version with it sometimes this next week.

**Comment by lucasvr** [comment]
Hi Matthew. It looks like Landsat metadata fields have recently changed:
https://landsat.usgs.gov/may-2018-landsat-level-1-metadata-changes

I wonder if that could be the reason why ingestion is failing?

**Comment by matthewhanson** [comment]
@lucasvr I think it's related to their metadata changes. We use a CSV from USGS to ingest the data, and not only did some fields in that change, but the entire ordering of the file was reversed.

I've got some updates and deploying a new version now that has the latest [STAC](https://github.com/radiantearth/stac-spec) updates.

Also, this repo, landsat-api, is deprecated, the correct repo to post further issues is [sat-api](https://github.com/sat-utils/sat-api)
